name: IngamePluginDeactivation
main: com.comze_instancelabs.ingameplugindeactivation.Main
version: 1.0
author: InstanceLabs
permissions:
  plugindeact.deactivate:
    description: Gives access to deactivate a plugin.
  plugindeact.activate:
    description: Gives access to activate a plugin.
commands:
   deactivate:
      description: Deactivate a plugin
      usage: /deactivate [name]
      permission: plugindeact.deactivate
   deactivateplugin:
      description: Deactivate a plugin
      usage: /deactivateplugin [name]
      permission: plugindeact.deactivate
   dp:
      description: Deactivate a plugin
      usage: /dp [name]
      permission: plugindeact.deactivate
   activate:
      description: Activate a plugin
      usage: /activate [name]
      permission: plugindeact.activate